version: "3.9"

services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: railsdev
      MYSQL_USER: railsdev
      MYSQL_PASSWORD: railsdev
      TZ: "Asia/Tokyo"
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./data/mysql:/var/lib/mysql
      - ./data/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - db-store:/var/lib/redis
      - ./data/redis:/data

volumes:
  db-store:
