version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7.40
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: railsdev
      MYSQL_USER: railsdev
      MYSQL_PASSWORD: railsdev
    restart: always
    command: mysqld --skip-grant-tables --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
