version: "3.9"

services:
  # MySQL
  db:
    image: mysql:5.7.40
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: railsdev
      MYSQL_USER: railsdev
      MYSQL_PASSWORD: railsdev
    restart: always
    command: mysqld --skip-grant-tables --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./data/redis:/data
